name: nashwaluthfiya_124230016_pam_a
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3 
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  crypto: ^3.0.6
  path_provider: ^2.1.5
  http: ^1.5.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  path: ^1.8.3
  provider: ^6.1.5+1
  image_picker: ^1.1.2
  flutter_local_notifications: ^19.5.0
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  http: ^1.5.0
  google_maps_webservice: ^0.0.20-nullsafety.1
  
flutter:
  uses-material-design: true
